name: Telegram Message on Push
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            📢 **New Commit Push Alert** 📢
            
            **Commit by**: ${{ github.actor }}
            **Commit Message**: ${{ github.event.commits[0].message }}
            
            **Repository**: ${{ github.repository }}
            
            **View Changes**: [Click here to view commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
